# Minimale Planungs-Config für Franka Cube Stacking
# Verwendung: python plan.py --config-name plan_franka model_name=2026-02-02/10-04-17

defaults:
  - _self_
  - planner: cem

hydra:
  run:
    dir: plan_outputs/${now:%Y%m%d%H%M%S}_franka_gH${goal_H}

# Modell-Pfad (absoluter Pfad für Server)
ckpt_base_path: /home/tsp_jw/Desktop/dino_wm
model_name: null  # z.B. 2026-02-02/22-50-30
model_epoch: latest

# Planungs-Parameter
seed: 42
n_evals: 5
goal_source: 'dset'  # Ziel aus Dataset (kein Isaac Sim nötig!)
goal_H: 5
n_plot_samples: 5

debug_dset_init: false

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 0.5
  base: 2
  mode: last


# 2026-02-09/08-12-44