defaults:
  - _self_
  - env: point_maze
  - encoder: dino 
  - action_encoder: proprio
  - proprio_encoder: proprio
  - decoder: vqvae
  - predictor: vit
  - override hydra/launcher: submitit_slurm

# base path to save model outputs. Checkpoints will be saved to ${ckpt_base_path}/outputs.
ckpt_base_path: ./ # put absolute path here

hydra:
  run:
    dir: ${ckpt_base_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${ckpt_base_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    nodes: 1
    tasks_per_node: 1
    cpus_per_task: 8
    mem_gb: 512
    gres: "gpu:h100:1"
    timeout_min: 2880
    setup: ["export DEBUGVAR=$(scontrol show hostnames $SLURM_JOB_NODELIST)",
            export MASTER_ADDR="$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)",
            "export MASTER_PORT=$(for port in $(shuf -i 30000-65500 -n 20); do if [[ $(netstat -tupln 2>&1 | grep $port | wc -l) -eq 0 ]] ; then echo $port; break; fi; done;)",]

training:
  seed: 0
  epochs: 100  # von 50 erhöht für 1000-Episoden-Training (14.02.2026)
  batch_size: 8 #8 -> GPU nur bei ~60% #16 -> GPU Out of Memory #32 -> GPU Out of Memory # should >= nodes * tasks_per_node
  gradient_accumulation_steps: 4  # effektive Batch-Size = 8 * 4 = 32 (Paper-Standard)
  save_every_x_epoch: 1
  reconstruct_every_x_batch: 500
  num_reconstruct_samples: 6
  encoder_lr: 1e-6
  decoder_lr: 3e-4   # Paper-Wert (zurückgesetzt)
  predictor_lr: 5e-5  # Paper Table 12 (war 2e-4, ~16x zu hoch mit kleiner BS)
  action_encoder_lr: 5e-4

img_size: 224 # should be a multiple of 224
frameskip: 5  # Paper-Default (frameskip=2 führt zu near-identity Predictions)
concat_dim: 1

normalize_action: True

# action encoder
action_emb_dim: 10
num_action_repeat: 1

# proprio encoder
proprio_emb_dim: 10 
num_proprio_repeat: 1

num_hist: 3  # Paper-Default (konsistent halten für kontrollierte Experimente)
num_pred: 1 # only supports 1
has_predictor: True # set this to False for only training a decoder
has_decoder: True # set this to False for only training a predictor

model:
  _target_: models.visual_world_model.VWorldModel
  image_size: ${img_size}
  num_hist: ${num_hist}
  num_pred: ${num_pred}
  train_encoder: False
  train_predictor: True
  train_decoder: True

debug: False 

# Planning params for planning eval jobs launched during training
plan_settings: 
  # plan_cfg_path: conf/plan.yaml # set to null for no planning evals
  plan_cfg_path: null 
  planner: ['gd', 'cem']
  goal_source: ['dset', 'random_state']
  goal_H: [5]
  alpha: [0.1, 1]
