# Franka Cube Stack Environment für DINO WM
name: franka_cube_stack

args: []
kwargs: {}

# Dimensionen (für Planner)
# action_dim wird automatisch aus dem Datensatz erkannt (6D oder 8D)
# 6D: [x_start, y_start, z_start, x_end, y_end, z_end]
# 8D: [x_start, y_start, z_start, g_start, x_end, y_end, z_end, g_end]  (mit Gripper-State)
action_dim: 8  # 8 wenn track_gripper_state=true in der Datensammlung, sonst 6
state_dim: 14  # EEF states: [q1, q2, q3, q4, q5, q6, q7, q1', q2', q3', q4', q5', q6', q7'] (7 Gelenkwinkel_start + 7 Gelenkwinkel_end)
proprio_dim: 3 # EEF position (x, y, z)



# Dataset
dataset:
  # Merged: combined fields from both branches
  _target_: "datasets.franka_cube_stack_dset.load_franka_cube_stack_slice_train_val"
  n_rollout: null  # null = alle verfügbaren Rollouts laden
  normalize_action: ${normalize_action}
  # data_path: If FRANKA_DATA_PATH env var is set, use it; otherwise fallback to local path
  # Alt: primLogger_NEps500_ActInt10_RobOpac0_NCams4_NCube1 (500ep, ActInt10)
  # data_path: ${oc.env:FRANKA_DATA_PATH,/home/tsp_jw/Desktop/fcs_datasets/NEps500_RobOpac10_NPrim10_NCams4_NCube1/}
  data_path: "/media/tsp_jw/data/DINO_WM/fcs_datasets/20260221_2011_NEps1000_RobOpac0_NPrim20_NCams1_NCube1_EEFfix_TrackGrip"

  split_ratio: 0.9

  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: [224, 224]
  # # Optional: Weitere Parameter
  # num_hist: 2      # Anzahl Historien-Frames für Kontext
  # num_pred: 1      # Anzahl zu prädizierender Frames
  # frameskip: 2     # Frame-Subsampling (1 = alle Frames)

decoder_path: null
num_workers: 2

