# Hydra Config für Franka Cube Stacking Dataset
# Verwendung: python train.py env=franka_cube_stack
name: franka_cube_stack
args: []
kwargs: {}

load_dir: ""

dataset:
  _target_: "datasets.franka_cube_stack_dset.load_franka_cube_stack_slice_train_val"
  n_rollout: null  # null = alle verfügbaren Rollouts laden
  normalize_action: ${normalize_action}
  # data_path: ${oc.env:DATASET_DIR,./data}/franka_cube_stack
  data_path: /media/tsp_jw/fc8bca1b-cab8-4522-81d0-06172d2beae8/fcs_datasets/2026_01_13_1152_fcs_dset
  split_ratio: 0.9
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 0

