# Franka Cube Stack Environment für DINO WM
name: franka_cube_stack

args: []
kwargs: {}

# Dataset
dataset:
  _target_: datasets.franka_cube_stack_dset.get_franka_cube_stack_dset
  data_path: ${oc.env:FRANKA_DATA_PATH,/path/to/plain_data}
  img_size: [224, 224]
  train_ratio: 0.8

# Optional: Decoder-Pfad
decoder_path: null
