# Hydra Config für Franka Cube Stacking Dataset
# Verwendung: python train.py env=franka_cube_stack
name: franka_cube_stack
args: []
kwargs: {}

load_dir: ""

dataset:
  _target_: "datasets.franka_cube_stack_dset.load_franka_cube_stack_slice_train_val"
  n_rollout: null  # null = alle verfügbaren Rollouts laden
  normalize_action: ${normalize_action}
  # data_path: ${oc.env:DATASET_DIR,./data}/franka_cube_stack
  data_path: /home/tsp_jw/Desktop/isaacsim/00_my_envs/Franka_Cube_Stacking_JW/dataset/franka_cube_stack_ds
  split_ratio: 0.9
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 0  # Reduziert wegen Segfault bei multiprocessing

