_target_: models.dino.DinoV2Encoder
name: "dinov2_vits14_reg"  # _reg Variante: behebt High-Norm "Register-Token" Artefakte
feature_key: "x_norm_patchtokens"
normalize_features: true  # L2-Normalisierung der Patch-Features (Fokus auf Richtung statt Magnitude)
